import { neon } from "@neondatabase/serverless";

if (!process.env.DATABASE_URL) {
  console.log("No DATABASE_URL set, skipping seeding.");
  process.exit(0);
}

const sql = neon(process.env.DATABASE_URL);

async function initAndSeed() {
  console.log("Ensuring all tables exist...");

  await sql`CREATE TABLE IF NOT EXISTS academy_posts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    skill text NOT NULL,
    category text NOT NULL,
    level text NOT NULL
  )`;

  await sql`CREATE TABLE IF NOT EXISTS atlas_posts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country text NOT NULL,
    status text NOT NULL,
    year text NOT NULL,
    highlight text NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL
  )`;

  await sql`CREATE TABLE IF NOT EXISTS devops_projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text,
    category text,
    description text,
    image_url text,
    ppt_url text,
    github_url text,
    technologies text,
    highlights text,
    status text
  )`;

  await sql`CREATE TABLE IF NOT EXISTS devops_posts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    category text NOT NULL,
    description text NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL
  )`;

  await sql`CREATE TABLE IF NOT EXISTS movies (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    genre text NOT NULL,
    rating real NOT NULL,
    trailer_url text,
    poster_url text,
    synopsis text,
    is_featured boolean DEFAULT false
  )`;

  await sql`CREATE TABLE IF NOT EXISTS timeline_posts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    category text NOT NULL,
    description text NOT NULL,
    year text,
    event_date text,
    created_at timestamp DEFAULT now() NOT NULL
  )`;

  await sql`CREATE TABLE IF NOT EXISTS travel_posts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country text NOT NULL,
    city text NOT NULL,
    description text
  )`;

  await sql`CREATE TABLE IF NOT EXISTS project_media (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id integer,
    filename text NOT NULL,
    mime_type text NOT NULL,
    file_size integer NOT NULL,
    file_data bytea NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
  )`;

  console.log("Checking row counts...");

  // 1. devops_projects
  const devopsCount = Number((await sql`SELECT COUNT(*)::int AS count FROM devops_projects`)[0].count);
  if (devopsCount === 0) {
    console.log("Seeding devops_projects...");
    const devopsData = [
      {
        id: 1,
        title: "Networking & OSI Model Master Notes",
        category: "Notes",
        description: "Comprehensive engineering notebook covering Layer 2 to Layer 7 packet transport, TCP handshakes, NAT traversal, and common networking diagnostics with curl and dig.",
        image_url: "/dev-real-2102415.jpg",
        ppt_url: "https://www.youtube.com/watch?v=X48VuDVv0do",
        github_url: "https://github.com/sohail-24/networking-runbooks",
        technologies: "TCP/IP, OSI 7-Layer, DNS, NAT, Wireshark, BGP",
        highlights: JSON.stringify({
          video_url: "https://www.youtube.com/watch?v=X48VuDVv0do",
          video_duration: "14:20",
          pdf_url: "/Master-Notes.pdf",
          takeaways: "Understand packet lifecycles, ARP tables, and why 80% of distributed system outages trace back to DNS and MTU misconfigurations.",
          links: [
            { title: "GitHub Runbook Repo", url: "https://github.com/sohail-24/networking-runbooks", type: "github" },
            { title: "RFC 1918 Private Addressing", url: "https://datatracker.ietf.org/doc/html/rfc1918", type: "docs" },
            { title: "OSI Architecture Slides", url: "https://slides.com/sohail/osi-model", type: "slides" }
          ]
        }),
        status: "Published Note",
      },
      {
        id: 2,
        title: "VPC Subnetting & CIDR Calculation Deep Dive",
        category: "Networking",
        description: "Step-by-step architectural breakdown of calculating subnets, public vs private routing tables, internet gateways, and NAT gateway placement for zero-trust VPC design.",
        image_url: "/dev-real-3183150.jpg",
        ppt_url: "https://www.youtube.com/watch?v=s_Ntt6eTn94",
        github_url: "https://github.com/sohail-24/terraform-aws-vpc-modular",
        technologies: "VPC, CIDR, Subnets, Route Tables, IGW, NAT",
        highlights: JSON.stringify({
          video_url: "https://www.youtube.com/watch?v=s_Ntt6eTn94",
          video_duration: "18:45",
          takeaways: "Master slash-notation subnetting (/24 vs /28), understand AWS reserved IPs (.0 to .3 and .255), and enforce strict egress filtering.",
          links: [
            { title: "Terraform VPC Module", url: "https://github.com/sohail-24/terraform-aws-vpc-modular", type: "github" },
            { title: "AWS VPC Architecture Guide", url: "https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html", type: "docs" }
          ]
        }),
        status: "Active",
      },
      {
        id: 3,
        title: "Multi-AZ High Availability Architecture on AWS",
        category: "AWS",
        description: "Production multi-availability zone infrastructure deploying Application Load Balancers, auto-scaling EC2 groups, and Amazon Aurora multi-master databases with automated failover.",
        image_url: "/dev-real-2582937.jpg",
        ppt_url: "https://www.youtube.com/watch?v=Ia-UEYYR44s",
        github_url: "https://github.com/sohail-24/aws-multi-az-reference",
        technologies: "AWS, EC2, ALB, Auto Scaling, Aurora, CloudWatch",
        highlights: JSON.stringify({
          video_url: "https://www.youtube.com/watch?v=Ia-UEYYR44s",
          video_duration: "22:10",
          takeaways: "Eliminate single points of failure across data centers with multi-region health checks and sub-minute database replica failovers.",
          links: [
            { title: "Infrastructure Blueprint Repo", url: "https://github.com/sohail-24/aws-multi-az-reference", type: "github" },
            { title: "AWS Well-Architected Framework", url: "https://aws.amazon.com/architecture/well-architected/", type: "docs" }
          ]
        }),
        status: "Production Ready",
      },
      {
        id: 4,
        title: "SohailShop",
        category: "Production-Grade E-Commerce / Cloud-Native Backend",
        description: "I designed and built a production-grade Django e-commerce backend from scratch and then deployed it using DevOps practices across two Kubernetes environments: a self-managed kubeadm cluster on EC2 and a production-ready AWS EKS setup.",
        image_url: "/projects/temporary/sohail-shop-desktop.v2.jpg",
        ppt_url: "https://www.youtube.com/watch?v=X48VuDVv0do",
        github_url: "",
        technologies: "Django, Python, PostgreSQL, Docker, Nginx, Gunicorn, Redis, Kubernetes, kubeadm, Calico, Helm, GitHub Actions, ArgoCD, Terraform, AWS EKS, AWS S3, ALB Ingress, IAM / IRSA",
        highlights: JSON.stringify({
          video_url: "https://www.youtube.com/watch?v=X48VuDVv0do",
          video_duration: "25:30",
          takeaways: "One push → automated build → infrastructure update → GitOps synchronization → Kubernetes deployment across kubeadm and AWS EKS.",
          links: [
            { title: "Kubeadm & Helm Manifests", url: "https://github.com/sohail-24/devops-ecommerce-kubeadm", type: "github" },
            { title: "Terraform EKS Platform", url: "https://github.com/sohail-24/terraform-eks-platform", type: "github" }
          ]
        }),
        status: "Live",
      },
      {
        id: 5,
        title: "Deploy a Static Website on AWS S3 & CloudFront",
        category: "Learn & Test Projects",
        description: "Hands-on guided lab: Provision an S3 bucket configured for static hosting, associate an ACM SSL certificate, route custom DNS with Route 53, and enable edge caching via CloudFront CDN.",
        image_url: "/dev-desk-1.jpg",
        ppt_url: "https://www.youtube.com/watch?v=mls8tii06cE",
        github_url: "https://github.com/sohail-24/s3-cloudfront-starter",
        technologies: "AWS S3, CloudFront, Route 53, ACM SSL, OAC",
        highlights: JSON.stringify({
          video_url: "https://www.youtube.com/watch?v=mls8tii06cE",
          video_duration: "16:05",
          takeaways: "Enforce Origin Access Control (OAC) to completely disallow public S3 bucket reads while serving global visitors in under 30ms.",
          links: [
            { title: "Starter Lab Code", url: "https://github.com/sohail-24/s3-cloudfront-starter", type: "github" },
            { title: "CloudFront OAC Guide", url: "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html", type: "docs" }
          ]
        }),
        status: "Beginner Lab",
      },
      {
        id: 6,
        title: "Deploy on Kubernetes: Rolling Zero-Downtime Updates",
        category: "Learn & Test Projects",
        description: "Hands-on guided lab: Containerize a Python web application, craft Kubernetes Deployment and Service YAMLs, configure readiness and liveness probes, and test zero-downtime rolling updates with Apache Bench.",
        image_url: "/dev-real-2102415.jpg",
        ppt_url: "https://www.youtube.com/watch?v=VnvRFRk_51k",
        github_url: "https://github.com/sohail-24/k8s-rolling-deploy-lab",
        technologies: "Kubernetes, Docker, Readiness Probes, Rolling Updates, Helm",
        highlights: JSON.stringify({
          video_url: "https://www.youtube.com/watch?v=VnvRFRk_51k",
          video_duration: "20:15",
          takeaways: "Configure maxSurge and maxUnavailable, observe pod replacement in real-time with kubectl rollout status, and benchmark with zero HTTP 502 errors.",
          links: [
            { title: "Lab Kubernetes Manifests", url: "https://github.com/sohail-24/k8s-rolling-deploy-lab", type: "github" },
            { title: "Kubernetes Rolling Update Docs", url: "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment", type: "docs" }
          ]
        }),
        status: "Hands-on Lab",
      },
      {
        id: 7,
        title: "Day-1 — Networking Fundamentals",
        category: "Networking",
        description: "Foundational breakdown of computer networking for DevOps engineers: OSI 7-layer model, packet lifecycles, TCP/IP vs UDP, DNS resolution, and core diagnostics.",
        image_url: "/dev-real-2102415.jpg",
        ppt_url: "https://www.jioaicloud.com/l/?u=DZCMz__IiBpVJkJgHfDGLuAvKlxmlF2lNC-S4hVdVx-M-0WqbbzB3U6j-94b6_xOXPz",
        github_url: "https://github.com/sohail-24/networking-runbooks",
        technologies: "Networking Fundamentals, OSI Model, TCP/IP, DNS",
        highlights: JSON.stringify({
          name: "Networking Fundamentals",
          video_url: "https://www.jioaicloud.com/l/?u=DZCMz__IiBpVJkJgHfDGLuAvKlxmlF2lNC-S4hVdVx-M-0WqbbzB3U6j-94b6_xOXPz",
          video_duration: "14:20",
          pdf_url: "/Master-Notes.pdf",
          takeaways: "Master the OSI model, packet lifecycles, and core networking troubleshooting with curl, dig, and ping.",
          links: [
            { title: "GitHub Runbook Repo", url: "https://github.com/sohail-24/networking-runbooks", type: "github" },
            { title: "OSI Architecture Slides", url: "https://slides.com/sohail/osi-model", type: "slides" }
          ]
        }),
        status: "Active",
      },
    ];

    for (const d of devopsData) {
      await sql`
        INSERT INTO devops_projects (id, title, category, description, image_url, ppt_url, github_url, technologies, highlights, status)
        VALUES (${d.id}, ${d.title}, ${d.category}, ${d.description}, ${d.image_url}, ${d.ppt_url}, ${d.github_url}, ${d.technologies}, ${d.highlights}, ${d.status})
      `;
    }
    await sql`SELECT setval(pg_get_serial_sequence('devops_projects', 'id'), (SELECT MAX(id) FROM devops_projects), true)`;
    console.log("✓ devops_projects seeded.");
  }

  // 2. movies
  const moviesCount = Number((await sql`SELECT COUNT(*)::int AS count FROM movies`)[0].count);
  if (moviesCount === 0) {
    console.log("Seeding movies...");
    const moviesData = [
      {
        id: 1,
        title: "Interstellar",
        genre: "Sci-Fi",
        rating: 9.5,
        trailer_url: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
        poster_url: "/cinema/posters/interstellar.jpg",
        synopsis: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
        is_featured: false,
      },
      {
        id: 2,
        title: "Inception",
        genre: "Sci-Fi",
        rating: 9.2,
        trailer_url: "https://www.youtube.com/watch?v=YoHD9XEInc0",
        poster_url: "/cinema/posters/inception.jpg",
        synopsis: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        is_featured: false,
      },
      {
        id: 3,
        title: "The Matrix",
        genre: "Sci-Fi",
        rating: 9.0,
        trailer_url: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
        poster_url: "/cinema/posters/matrix.jpg",
        synopsis: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        is_featured: false,
      },
      {
        id: 4,
        title: "The Dark Knight",
        genre: "Action",
        rating: 9.4,
        trailer_url: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
        poster_url: "/cinema/posters/dark-knight.jpg",
        synopsis: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        is_featured: false,
      },
      {
        id: 5,
        title: "Oppenheimer",
        genre: "Drama",
        rating: 8.9,
        trailer_url: "https://www.youtube.com/watch?v=uYPbbksJxIg",
        poster_url: "/cinema/posters/oppenheimer.jpg",
        synopsis: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
        is_featured: true,
      },
      {
        id: 6,
        title: "Blade Runner 2049",
        genre: "Sci-Fi",
        rating: 8.8,
        trailer_url: "https://www.youtube.com/watch?v=gCcx85zbxz4",
        poster_url: "/cinema/posters/blade-runner.jpg",
        synopsis: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
        is_featured: false,
      },
    ];

    for (const m of moviesData) {
      await sql`
        INSERT INTO movies (id, title, genre, rating, trailer_url, poster_url, synopsis, is_featured)
        VALUES (${m.id}, ${m.title}, ${m.genre}, ${m.rating}, ${m.trailer_url}, ${m.poster_url}, ${m.synopsis}, ${m.is_featured})
      `;
    }
    await sql`SELECT setval(pg_get_serial_sequence('movies', 'id'), (SELECT MAX(id) FROM movies), true)`;
    console.log("✓ movies seeded.");
  }

  // 3. academy_posts
  const academyCount = Number((await sql`SELECT COUNT(*)::int AS count FROM academy_posts`)[0].count);
  if (academyCount === 0) {
    console.log("Seeding academy_posts...");
    const academyData = [
      { id: 1, skill: "Kubernetes & EKS", category: "Cloud Infrastructure", level: "Advanced" },
      { id: 2, skill: "Terraform & IaC", category: "DevOps & Automation", level: "Advanced" },
      { id: 3, skill: "Docker & Microservices", category: "Containerization", level: "Expert" },
      { id: 4, skill: "AWS Architecture", category: "Cloud Computing", level: "Advanced" },
      { id: 5, skill: "React & TypeScript", category: "Frontend Engineering", level: "Expert" },
      { id: 6, skill: "Linux & Shell Automation", category: "Systems", level: "Expert" },
      { id: 7, skill: "ArgoCD & GitOps", category: "Continuous Delivery", level: "Advanced" },
      { id: 8, skill: "PostgreSQL & Databases", category: "Databases", level: "Intermediate" },
    ];
    for (const a of academyData) {
      await sql`
        INSERT INTO academy_posts (id, skill, category, level)
        VALUES (${a.id}, ${a.skill}, ${a.category}, ${a.level})
      `;
    }
    await sql`SELECT setval(pg_get_serial_sequence('academy_posts', 'id'), (SELECT MAX(id) FROM academy_posts), true)`;
    console.log("✓ academy_posts seeded.");
  }

  // 4. timeline_posts
  const timelineCount = Number((await sql`SELECT COUNT(*)::int AS count FROM timeline_posts`)[0].count);
  if (timelineCount === 0) {
    console.log("Seeding timeline_posts...");
    const timelineData = [
      {
        id: 4,
        title: "Bachelor of Engineering — Electronics & Instrumentation",
        category: "Education",
        description: "Completed a Bachelor of Engineering in Electronics and Instrumentation Engineering at Muffakham Jah College of Engineering and Technology (2019 – 2023), building the engineering foundation that later evolved into cloud infrastructure, automation, and platform engineering.",
        year: "2023",
        event_date: "2023-08-01",
        created_at: "2023-08-01 00:00:00",
      },
      {
        id: 5,
        title: "Saudi Arabia Journey & AWS / DevOps Genesis",
        category: "Exploration & Learning",
        description: "During my Saudi Arabia journey, I began a focused transition into AWS Cloud and DevOps, moving from an engineering foundation toward hands-on infrastructure, automation, and cloud-native systems.",
        year: "2024",
        event_date: "2024-03-10",
        created_at: "2024-03-10 00:00:00",
      },
      {
        id: 2,
        title: "6-Month DevOps Engineering Internship",
        category: "Career & Systems",
        description: "Completed an intensive 6-month industry internship at Visys Cloud Technologies. Built and automated CI/CD pipelines using GitHub Actions, Jenkins, Docker, and Helm; provisioned AWS infrastructure with Terraform; deployed containerized workloads to Amazon EKS and self-managed Kubernetes (kubeadm); and automated Linux administration with Ansible and Bash.",
        year: "2025",
        event_date: "2025-12-20",
        created_at: "2025-12-20 00:00:00",
      },
      {
        id: 6,
        title: "SohailShop — Production Kubernetes Platform",
        category: "Systems & Cloud",
        description: "Engineered a production-ready Django e-commerce platform containerized with Docker and deployed across both self-managed kubeadm and Amazon EKS environments using Terraform, Helm, ArgoCD GitOps, and GitHub Actions.",
        year: "2026",
        event_date: "2026-01-15",
        created_at: "2026-01-15 00:00:00",
      },
      {
        id: 7,
        title: "Fresh Flow — Real-World Application & Transactions",
        category: "Production Systems",
        description: "Built and launched Fresh Flow as a real-world application now serving real users and handling real transactions, transitioning from hands-on infrastructure and internship engineering into operating a live, customer-facing product.",
        year: "2026",
        event_date: "2026-03-20",
        created_at: "2026-03-20 00:00:00",
      },
      {
        id: 1,
        title: "Timeline CMS Created",
        category: "Platform",
        description: "Built a dynamic timeline powered by Cloudflare Workers and D1 Database",
        year: "2026",
        event_date: "2026-06-16",
        created_at: "2026-06-16 00:00:00",
      },
    ];
    for (const t of timelineData) {
      await sql`
        INSERT INTO timeline_posts (id, title, category, description, year, event_date, created_at)
        VALUES (${t.id}, ${t.title}, ${t.category}, ${t.description}, ${t.year}, ${t.event_date}, ${t.created_at}::timestamp)
      `;
    }
    await sql`SELECT setval(pg_get_serial_sequence('timeline_posts', 'id'), (SELECT MAX(id) FROM timeline_posts), true)`;
    console.log("✓ timeline_posts seeded.");
  }

  // 5. atlas_posts
  const atlasCount = Number((await sql`SELECT COUNT(*)::int AS count FROM atlas_posts`)[0].count);
  if (atlasCount === 0) {
    console.log("Seeding atlas_posts...");
    const atlasData = [
      {
        id: 1,
        country: "Saudi Arabia",
        status: "Explored",
        year: "2024",
        highlight: "Spiritual journey and exploration of Riyadh, Mecca, and Medina.",
        created_at: "2024-04-01 00:00:00",
      },
      {
        id: 2,
        country: "United Arab Emirates",
        status: "Visited",
        year: "2024",
        highlight: "Explored Dubai's architectural wonders, tech hubs, and desert landscapes.",
        created_at: "2024-05-15 00:00:00",
      },
      {
        id: 3,
        country: "India",
        status: "Home",
        year: "2023",
        highlight: "Engineering degree completion and software development genesis.",
        created_at: "2023-01-01 00:00:00",
      },
    ];
    for (const a of atlasData) {
      await sql`
        INSERT INTO atlas_posts (id, country, status, year, highlight, created_at)
        VALUES (${a.id}, ${a.country}, ${a.status}, ${a.year}, ${a.highlight}, ${a.created_at}::timestamp)
      `;
    }
    await sql`SELECT setval(pg_get_serial_sequence('atlas_posts', 'id'), (SELECT MAX(id) FROM atlas_posts), true)`;
    console.log("✓ atlas_posts seeded.");
  }

  console.log("All tables initialized and seeded successfully.");
}

initAndSeed().catch((err) => {
  console.error("Seeding error:", err);
  process.exit(1);
});
